// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hngpgyplejxnanmzyxhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuZ3BneXBsZWp4bmFubXp5eGhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTA5MzIsImV4cCI6MjA2NzcyNjkzMn0.TauqfwU79ROZc_-dxc-ZLjkqL2qlKhQpU3b6ZsAeHAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});